steps:

  ################################################################################
  # vsts-task-lib
  ################################################################################

  # npm install
  - task: Npm@1
    displayName: (vsts-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 5
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 5.10.1
    condition: and(succeeded(), ne(variables.os, 'windows'))
    inputs:
      versionSpec: "5.10.1"
  - powershell: |
      & "$(build.sourcesDirectory)/res/UseNode5.ps1"
    displayName: (vsts-task-lib) use node 5.10.1
    condition: and(succeeded(), eq(variables.os, 'windows'))

  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (vsts-task-lib) node make.js test  

  # use node 6
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: (vsts-task-lib) node make.js test
    workingDirectory: node

  ################################################################################
  # VstsTaskSdk
  ################################################################################

  # npm install
  - task: Npm@1
    displayName: (VstsTaskSdk) npm install
    condition: and(succeeded(), eq(variables.os, 'windows'))
    inputs:
      command: install
      workingDir: powershell

  # npm test
  - script: npm test
    displayName: (VstsTaskSdk) npm test
    condition: and(succeeded(), eq(variables.os, 'windows'))
    workingDirectory: powershell
