phases:

########################################
# Windows
########################################
- phase: Windows
  queue:
    demands: agent.os -equals Windows_NT

  steps:

  ########################################
  # vsts-task-lib
  ########################################

  # npm install
  - script: npm install
    displayName: (vsts-task-lib) npm install
    workingDirectory: node

  # use node 5
  - powershell: ./res/UseNode5.ps1
    displayName: (vsts-task-lib) use node 5.10.1

  # build/test
  - script: node make.js test
    displayName: (vsts-task-lib) node make.js test
    workingDirectory: node

  # use node 6
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: (vsts-task-lib) node make.js test
    workingDirectory: node

  ########################################
  # VstsTaskSdk
  ########################################

  # npm install
  - script: npm install
    displayName: (VstsTaskSdk) npm install
    workingDirectory: powershell

  # npm test
  - script: npm test
    displayName: (VstsTaskSdk) npm test
    workingDirectory: powershell

########################################
# macOS
########################################
- phase: macOS
  queue:
    demands: agent.os -equals Darwin

  steps:

  ########################################
  # vsts-task-lib
  ########################################

  # npm install
  - script: npm install
    displayName: npm install
    workingDirectory: node

  # use node 5
  - task: NodeTool@0
    displayName: use node 5.10.1
    inputs:
      versionSpec: "5.10.1"

  # build/test
  - script: node make.js test
    displayName: node make.js test
    workingDirectory: node

  # use node 6
  - task: NodeTool@0
    displayName: use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: node make.js test
    workingDirectory: node

########################################
# Linux
########################################
- phase: Linux
  queue:
    demands: agent.os -equals Linux

  steps:

  ########################################
  # vsts-task-lib
  ########################################

  # npm install
  - script: npm install
    displayName: npm install
    workingDirectory: node

  # use node 5
  - task: NodeTool@0
    displayName: use node 5.10.1
    inputs:
      versionSpec: "5.10.1"

  # build/test
  - script: node make.js test
    displayName: node make.js test
    workingDirectory: node

  # use node 6
  - task: NodeTool@0
    displayName: use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: node make.js test
    workingDirectory: node
