phases:
- phase: Windows
  queue:
    demands: agent.os -equals Windows_NT

  steps:
  ########################################
  # vsts-task-lib (Windows)
  ########################################

  # npm install
  - script: npm install
    displayName: (vsts-task-lib) npm install
    workingDirectory: node

  # use node 5
  - powershell: . res/UseNode5.ps1
    name: (vsts-task-lib) use node 5.10.1

  # build/test
  - script: node make.js test
    name: (vsts-task-lib) node make.js test
    workingDirectory: node

  # use node 6
  - task: NodeTool@0
    name: (vsts-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    name: (vsts-task-lib) node make.js test
    workingDirectory: node

  ########################################
  # VstsTaskSdk (Windows)
  ########################################

  # npm install
  - script: npm install
    name: (VstsTaskSdk) npm install
    workingDirectory: powershell

  # npm test
  - script: npm test
    name: (VstsTaskSdk) npm test
    workingDirectory: powershell

- phase: macOS
  queue:
    demands: agent.os -equals Darwin

  steps:
  ########################################
  # vsts-task-lib (macOS)
  ########################################

  # npm install
  - script: npm install
    displayName: npm install
    workingDirectory: node

  # use node 5
  - task: NodeTool@0
    name: use node 5.10.1
    inputs:
      versionSpec: "5.10.1"

  # build/test
  - script: node make.js test
    name: node make.js test
    workingDirectory: node

  # use node 6
  - task: NodeTool@0
    name: use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    name: node make.js test
    workingDirectory: node

- phase: Linux
  queue:
    demands: agent.os -equals Darwin

  steps:
  ########################################
  # vsts-task-lib (Linux)
  ########################################

  # npm install
  - script: npm install
    displayName: npm install
    workingDirectory: node

  # use node 5
  - task: NodeTool@0
    name: use node 5.10.1
    inputs:
      versionSpec: "5.10.1"

  # build/test
  - script: node make.js test
    name: node make.js test
    workingDirectory: node

  # use node 6
  - task: NodeTool@0
    name: use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    name: node make.js test
    workingDirectory: node
