jobs:
  - name: Build vsts-task-lib
    steps:
      # npm install
      # - task: Npm@1.*
      #   name: npm install
      #   inputs:
      #     command: install
      #     workingDir: node
      - task: CmdLine@1.*
        name: npm install
        inputs:
          filename: npm
          arguments: install
          workingFolder: node

      # use node 5
      - task: NodeTool@0.*
        name: use node 5.10.1
        condition: and(succeeded(), ne(variables.os, 'win'))
        inputs:
          versionSpec: "5.10.1"
      - task: CmdLine@1.*
        name: use node 5.10.1
        condition: and(succeeded(), eq(variables.os, 'win'))
        inputs:
          filename: powershell.exe
          arguments: -noninteractive -noprofile -file "$(build.sourcesDirectory)/res/UseNode5.ps1"

      # build/test
      - task: CmdLine@1.*
        name: node make.js test
        inputs:
          filename: node
          arguments: make.js test
          workingFolder: node

      # use node 6
      - task: NodeTool@0.*
        name: use node 6.10.3
        inputs:
          versionSpec: "6.10.3"

      # build/test
      - task: CmdLine@1.*
        name: node make.js test
        inputs:
          filename: node
          arguments: make.js test
          workingFolder: node
  # - name: Build VstsTaskSdk
  #   steps:
  #     # - task: Npm@1.*
  #     #   name: npm install
  #     #   inputs:
  #     #     command: install
  #     #     workingDir: powershell
  #     - task: CmdLine@1.*
  #       name: npm install
  #       inputs:
  #         filename: npm
  #         arguments: install
  #         workingFolder: powershell
  #     - task: CmdLine@1.*
  #       name: npm test
  #       inputs:
  #         filename: npm
  #         arguments: test
  #         workingFolder: powershell
